RocketWorkflow/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RocketWorkflow.Models;
using Stripe;

namespace RocketWorkflow.Controllers
{
    public class ClientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }
        public ActionResult ClientPortal()
        {
            var currentUserId = User.Identity.GetUserId();
            if (currentUserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Where(c => c.ApplicationUserId == currentUserId).Single();
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }
        public ActionResult Charge()
        {
            var stripePublishKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            ViewBag.StripePublishKey = stripePublishKey;
            return View();
        }
        [HttpPost]
        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = 500,//charge in cents
                Description = "Sample Charge",
                Currency = "usd",
                CustomerId = customer.Id
            });

            

            return View();
        }


        // GET: Clients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        public ActionResult CreateClient()
        {

            return RedirectToAction("Create");
        }



        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,Email,PhoneNumber,BirthDate,SpouseId,HouseNumber,StreetName,City,State,ZipCode,ApplicationUserId")] Client client)
        {

            if (ModelState.IsValid)
            {
                client.ApplicationUserId = User.Identity.GetUserId();
                
                db.Clients.Add(client);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("ClientPortal");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int id)
        {
            if (id < 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Where(c => c.ClientId.Equals(id)).FirstOrDefault();
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,FirstName,LastName,Email,PhoneNumber,BirthDate,SpouseId,HouseNumber,StreetName,City,State,ZipCode")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RocketWorkflow/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RocketWorkflow.Models;
using RocketWorkflow.Models.ViewModels;

namespace RocketWorkflow.Controllers
{
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            MainViewModel JobInfo = new MainViewModel()
            { 
                JobsList = new List<Job>(),
            };
            JobInfo.JobsList = db.Jobs.ToList();
        
            return View(JobInfo);
        }

        public ActionResult ProjectView(int? id)
        {
            var job = db.Jobs.Where(j => j.JobId == id).SingleOrDefault();
            return View(job);
        }
        
        // GET: Jobs/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        //public List<Client> FormatClientNames()
        //{

        //    List<Client> ClientsList = new List<Client>();
        //    foreach (var client in db.Clients)
        //    {
        //        var name = (client.FirstName + " " + client.LastName);
        //        client.FullName = name;
        //        ClientsList.Add(client);
        //    }
        //    return ClientsList;
        //}

        //public List<Client> ClientsList()
        //{
        //    List<Client> ClientsList = new List<Client>();
        //    foreach (var client in db.Clients)
        //    {
        //    ClientsList.Add(client);
        //    }
        //    return ClientsList;
        //}

        //public List<string> ClientNamesList()
        //{
        //    List<string> ClientNamesList = new List<string>();
        //    foreach (var client in db.Clients)
        //    {
        //        ClientNamesList.Add(client.FullName);
        //    }
        //    return ClientNamesList;
        //}



        // GET: Jobs/Create
        public ActionResult Create()
        {
           
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "FullName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,JobName,AssignedEmployee,DueDate,CompleteTime,Fee,IsComplete,IsArchived,BillingComplete,,ClientId")] Job job)
        {
            if (ModelState.IsValid)
            {
                
                db.Jobs.Add(job);
                try
                { 
                db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            return View(job);
            //ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ApplicationUserId", job.ClientId);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "FullName", job.ClientId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,ClientId,JobName,AssignedEmployee,DueDate,CompleteTime,Fee,IsComplete,IsArchived,BillingComplete,SomeProp")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ApplicationUserId", job.ClientId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RocketWorkflow/Views/Shared/_AccountantLayout.cshtml
!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/bootstrapSlate.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">@Html.ActionLink("RocketWorkflow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <button type="button" class="btn btn-success">
                        <a class="nav-item">@Html.ActionLink("Client Portal", "ClientPortal", "Clients", new { area = "  " }, new { @class = "navbar-text" })</a>
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-success">
                        <a class="nav-item">@Html.ActionLink("Client Portal", "ClientPortal", "Clients", new { area = "  " }, new { @class = "navbar-text" })</a>
                    </button>
                </li>


            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RocketWorkflow/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/bootstrapSlate.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">@Html.ActionLink("RocketWorkflow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <button type="button" class="btn btn-success">
                        <a class="nav-item">@Html.ActionLink("Client Portal", "ClientPortal", "Clients", new { area = "  " }, new { @class = "navbar-text" })</a>
                    </button>
                </li>
                

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
    @*<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
            <a class="navbar-brand">@Html.ActionLink("Rocket Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <form class="form-inline">
                            <button class="btn btn-outline-success" type="button">@Html.ActionLink(" ", "ClientPortal", "Clients")Client Portal</button> </form>
                    </li>

                    <li class="nav-item active">
                        <form class="form-inline">
                            <button class="btn btn-outline-success" type="button">Client Portal @Html.ActionLink(" ", "ClientPortal", "Clients")</button> </form>
                    </li>
                </ul>
            </div>
        </nav>*@



    @*<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>*@















    @*<nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>*@

    @*<div class="container">
                <a class="navbar-brand" href="/">@Html.ActionLink("Rocket Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
                <div class="navbar" id="navbarSupportedContent">
                    <ul class="nav navbar-nav mr-auto">

                        <li class="nav-item">@Html.ActionLink("Client Portal", "ClientPortal", "Clients")</li>
                        <li class="nav-item">@Html.ActionLink("Client Portal", "ClientPortal", "Clients")</li>
                    </ul>
                        @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>*@

    @*<nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
            <div class="container" >
                <div class="navbar">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Rocket Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a class="navbar-brand">
                <div class="navbar" id="navbarSupportedContent">
                    <ul class="nav navbar-nav mr-auto">
                        <li>@Html.ActionLink("Client Portal", "ClientPortal", "Clients")</li>
                        <li>@Html.ActionLink("Client Portal", "ClientPortal", "Clients")</li>
                        <li>@Html.ActionLink("Client Portal", "ClientPortal", "Clients")</li>
                    </ul>
                </div>
                </a>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>*@

RocketWorkflow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/bootstrapSlate.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">@Html.ActionLink("RocketWorkflow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            


        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>

<div class="container body-content">
    @RenderBody()
    <hr />
    
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

RocketWorkflow/Views/Shared/_OfficeAdminLayout.cshtml
<!DOCTYPE html>

    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/bootstrapSlate.css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>


        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">@Html.ActionLink("RocketWorkflow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <button type="button" class="btn btn-success">
                            <a class="nav-item">@Html.ActionLink("Active Projects", "Index", "Jobs", new { area = "  " }, new { @class = "navbar-text" })</a>
                        </button>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-success">
                            <a class="nav-item">@Html.ActionLink("Clients", "Index", "Clients", new { area = "  " }, new { @class = "navbar-text" })</a>
                        </button>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-success">
                            <a class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { area = "  " }, new { @class = "navbar-text" })</a>
                        </button>
                    </li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>

        <div class="container body-content">
            @RenderBody()
            <hr />
           
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

@*<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Rocket Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                <li>@Html.ActionLink("Active Projects", "Index", "Jobs")</li>
                <li>@Html.ActionLink("Calendar", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
   
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>*@